apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-svdu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rwjb-tenant/rhtap-demo-app/hacbs-test-project-svdu@sha256:ee1a21bf4d0d7e7d8738281ff8f52054781a701c201f0099060564517e71cb5a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
